import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { useMemo } from "react";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { formatOrderDate, useOrderStore } from "@/lib/order-store";

export default function MonthsScreen() {
  const colors = useColors(); const router = useRouter(); const { hydrated, months, orders, selectedMonthId, selectMonth } = useOrderStore();
  const counts = useMemo(() => new Map(months.map((month) => [month.id, orders.filter((order) => order.monthId === month.id).length])), [months, orders]);
  if (!hydrated) return <ScreenContainer><View style={styles.center}><Text style={{ color: colors.muted }}>چاوەڕێ بە...</Text></View></ScreenContainer>;
  return <ScreenContainer edges={["top", "left", "right"]}><View style={styles.page}><View style={styles.header}><View><Text style={[styles.title, { color: colors.foreground }]}>مانگەکان</Text><Text style={[styles.subtitle, { color: colors.muted }]}>خۆکارانە بە پێی بەرواری ئۆردەر دروست دەبن</Text></View><View style={[styles.icon, { backgroundColor: colors.primary + "18" }]}><MaterialIcons name="calendar-month" size={23} color={colors.primary} /></View></View><FlatList data={months} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} showsVerticalScrollIndicator={false} renderItem={({ item }) => { const count = counts.get(item.id) ?? 0; const active = item.id === selectedMonthId; const latest = orders.filter((o) => o.monthId === item.id).sort((a, b) => b.createdAt.localeCompare(a.createdAt))[0]; return <Pressable onPress={() => { selectMonth(item.id); router.push("/"); }} style={({ pressed }) => [styles.card, { backgroundColor: colors.surface, borderColor: active ? colors.primary : colors.border }, pressed && styles.pressed]}><View style={styles.cardTop}><View style={[styles.monthIcon, { backgroundColor: active ? colors.primary + "20" : colors.background }]}><MaterialIcons name="description" size={22} color={active ? colors.primary : colors.muted} /></View><View style={{ flex: 1, marginHorizontal: 11 }}><Text style={[styles.monthName, { color: colors.foreground }]}>{item.name}</Text><Text style={[styles.meta, { color: colors.muted }]}>{count} ئۆردەر {latest ? `· نوێترین: ${formatOrderDate(latest.createdAt)}` : "· بەتاڵە"}</Text></View><MaterialIcons name="chevron-left" size={22} color={colors.muted} /></View><View style={[styles.badge, { backgroundColor: active ? colors.success + "18" : colors.background }]}><View style={[styles.dot, { backgroundColor: active ? colors.success : colors.muted }]} /><Text style={{ color: active ? colors.success : colors.muted, fontSize: 11, fontWeight: "700" }}>{active ? "مانگی هەڵبژێردراو" : "کرتە بکە بۆ بینین"}</Text></View></Pressable>; }} ListEmptyComponent={<View style={styles.center}><MaterialIcons name="event-note" size={45} color={colors.primary} /><Text style={[styles.empty, { color: colors.foreground }]}>هێشتا هیچ ئۆردەرێک نییە</Text><Text style={[styles.meta, { color: colors.muted }]}>کاتێک یەکەم ئۆردەر زیاد بکەیت، ئەم مانگە خۆکارانە دروست دەبێت.</Text></View>} /></View></ScreenContainer>;
}
const styles = StyleSheet.create({ page: { flex: 1, paddingHorizontal: 16 }, center: { flex: 1, alignItems: "center", justifyContent: "center", padding: 24 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingTop: 8, paddingBottom: 16 }, title: { fontSize: 24, fontWeight: "800", textAlign: "right" }, subtitle: { fontSize: 12, marginTop: 4, textAlign: "right" }, icon: { width: 46, height: 46, borderRadius: 15, alignItems: "center", justifyContent: "center" }, list: { paddingBottom: 30, gap: 11 }, card: { borderWidth: 1, borderRadius: 18, padding: 14 }, pressed: { opacity: 0.82, transform: [{ scale: 0.99 }] }, cardTop: { flexDirection: "row", alignItems: "center" }, monthIcon: { width: 44, height: 44, borderRadius: 14, alignItems: "center", justifyContent: "center" }, monthName: { fontSize: 15, fontWeight: "800", textAlign: "right" }, meta: { fontSize: 11, lineHeight: 19, marginTop: 4, textAlign: "right" }, badge: { alignSelf: "flex-start", flexDirection: "row", alignItems: "center", gap: 5, borderRadius: 10, paddingHorizontal: 8, paddingVertical: 6, marginTop: 12 }, dot: { width: 6, height: 6, borderRadius: 3 }, empty: { fontSize: 17, fontWeight: "800", marginTop: 12, textAlign: "center" } });
