import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import * as Notifications from "expo-notifications";
import { useEffect, useState } from "react";
import { Alert, Pressable, ScrollView, Share, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { useThemeContext } from "@/lib/theme-provider";
import { useOrderStore } from "@/lib/order-store";
import { downloadCloudBackup, getSession, signIn, signOut, signUp, shouldAutoBackup, uploadCloudBackup } from "@/lib/cloud-backup";

const SETTINGS_KEY = "orderakan.settings.v2";
type Frequency = "daily" | "monthly" | "never";

export default function SettingsScreen() {
  const colors = useColors(); const { colorScheme, setColorScheme } = useThemeContext();
  const { exportBackup, importBackup, trash, restoreOrder, emptyTrash } = useOrderStore();
  const [frequency, setFrequency] = useState<Frequency>("never"); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [sessionEmail, setSessionEmail] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  useEffect(() => { AsyncStorage.getItem(SETTINGS_KEY).then((raw) => { try { const v = raw ? JSON.parse(raw) : {}; if (v.frequency) setFrequency(v.frequency); if (v.theme) setColorScheme(v.theme); } catch {} }); getSession().then((s) => setSessionEmail(s?.email ?? null)); }, [setColorScheme]);
  const setFreq = async (value: Frequency) => { setFrequency(value); await AsyncStorage.setItem(SETTINGS_KEY, JSON.stringify({ frequency: value, theme: colorScheme })); await Notifications.cancelAllScheduledNotificationsAsync(); if (value !== "never") { const permission = await Notifications.requestPermissionsAsync(); if (permission.granted) await Notifications.scheduleNotificationAsync({ content: { title: "💾 باکئەپ بکە!", body: "تکایە بۆ پاراستنی زانیاریەکانت باکئەپ بکە" }, trigger: value === "daily" ? { type: Notifications.SchedulableTriggerInputTypes.DAILY, hour: 20, minute: 0 } : { type: Notifications.SchedulableTriggerInputTypes.MONTHLY, day: 1, hour: 20, minute: 0 } }); } };
  const login = async (register: boolean) => { if (!email.trim() || password.length < 6) { Alert.alert("زانیاری ناتەواوە", "Email و وشەی نهێنییەک بنووسە کە لانیکەم ٦ پیت بێت."); return; } setBusy(true); try { const s = register ? await signUp(email.trim(), password) : await signIn(email.trim(), password); setSessionEmail(s.email); setEmail(""); setPassword(""); Alert.alert("سەرکەوتوو بوو", register ? "هەژماری cloud دروست کرا." : "چوویتە ژوورەوە."); } catch (e) { Alert.alert("هەڵەی login", String(e).includes("EMAIL_EXISTS") ? "ئەم email ـە پێشتر هەیە؛ چوونەژوورەوە هەڵبژێرە." : "Email یان وشەی نهێنی هەڵەیە، یان Firebase ڕێک نەخراوە."); } finally { setBusy(false); } };
  const cloudBackup = async () => { if (!sessionEmail) { Alert.alert("چوونەژوورەوە پێویستە", "سەرەتا email و وشەی نهێنی بنووسە بۆ cloud backup."); return; } setBusy(true); try { await uploadCloudBackup(exportBackup()); Alert.alert("Backup سەرکەوتوو بوو", "هەموو داتاکانت لە Firebase Cloud Storage پارێزرا."); } catch { Alert.alert("هەڵە", "Backup نەکرا؛ پشکنینی ئینتەرنێت و Firebase بکە."); } finally { setBusy(false); } };
  const cloudRestore = async () => { if (!sessionEmail) { Alert.alert("چوونەژوورەوە پێویستە", "سەرەتا بچۆ ژوورەوە."); return; } setBusy(true); try { const payload = await downloadCloudBackup(); importBackup(payload); Alert.alert("گەڕێندرایەوە", "داتاکانت لە Cloud ـەوە بە سەرکەوتوویی گەڕێندرایەوە."); } catch { Alert.alert("هیچ Backup ـێک نییە", "لە Cloud ـدا backup نەدۆزرایەوە."); } finally { setBusy(false); } };
  useEffect(() => { if (!sessionEmail || frequency === "never") return; shouldAutoBackup(frequency).then((needed) => { if (needed) uploadCloudBackup(exportBackup()).catch(() => undefined); }).catch(() => undefined); }, [sessionEmail, frequency, exportBackup]);
  const openBackupMenu = () => Alert.alert("Backup ـی داتا", "چۆنیەتی backup ـی خۆکار هەڵبژێرە", [{ text: "رۆژانە", onPress: () => setFreq("daily") }, { text: "مانگانە", onPress: () => setFreq("monthly") }, { text: "هەرگیز", onPress: () => setFreq("never") }, { text: "پاشگەزبوونەوە", style: "cancel" }]);
  const localShare = async () => { await Share.share({ title: "Backup ـی ئۆردەرەکان", message: JSON.stringify(exportBackup(), null, 2) }); };
  const confirmTrash = () => Alert.alert("سڕینەوەی هەمیشەیی", "هەموو Trash دەسڕدرێتەوە؟", [{ text: "نەخێر", style: "cancel" }, { text: "بەڵێ", style: "destructive", onPress: emptyTrash }]);
  return <ScreenContainer edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.content}>
    <View style={styles.header}><View><Text style={[styles.title, { color: colors.foreground }]}>ڕێکخستن</Text><Text style={[styles.sub, { color: colors.muted }]}>بەڕێوەبردنی داتا و پاراستنی ئەپ</Text></View><MaterialIcons name="settings" size={28} color={colors.primary} /></View>
    <Section title="ڕووکار" icon="palette" colors={colors}><Row label="Dark mode" colors={colors}><Switch value={colorScheme === "dark"} onValueChange={async (v) => { const theme = v ? "dark" : "light"; setColorScheme(theme); await AsyncStorage.setItem(SETTINGS_KEY, JSON.stringify({ frequency, theme })); }} /></Row></Section>
    <Section title="Backup و Cloud" icon="cloud-upload" colors={colors}><Text style={[styles.help, { color: colors.muted }]}>Backup ـەکان لە Firebase Cloud Storage بە هەژماری تایبەتی تۆ پارێزراون.</Text><View style={styles.auth}><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="Email" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} /><TextInput value={password} onChangeText={setPassword} secureTextEntry placeholder="وشەی نهێنی" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} /><View style={styles.authRow}><SmallButton label="دروستکردنی هەژمار" color={colors.success} onPress={() => login(true)} /><SmallButton label="چوونەژوورەوە" color={colors.primary} onPress={() => login(false)} /></View></View>{sessionEmail ? <View style={[styles.logged, { backgroundColor: colors.success + "18" }]}><Text style={{ color: colors.success, flex: 1 }}>بەستراوە: {sessionEmail}</Text><Pressable onPress={async () => { await signOut(); setSessionEmail(null); }}><Text style={{ color: colors.error, fontWeight: "700" }}>دەرچوون</Text></Pressable></View> : null}<View style={styles.actions}><Action label="Backup" icon="backup" color={colors.primary} onPress={openBackupMenu} /><Action label="Restore" icon="cloud-download" color={colors.success} onPress={cloudRestore} /><Action label="کۆپی ناوخۆیی" icon="share" color={colors.warning} onPress={localShare} /></View><Text style={[styles.freqTitle, { color: colors.foreground }]}>یادخستنەوە: {frequency === "daily" ? "رۆژانە" : frequency === "monthly" ? "مانگانە" : "هەرگیز"}</Text><View style={styles.freqs}>{([['daily','رۆژانە'],['monthly','مانگانە'],['never','هەرگیز']] as const).map(([key, label]) => <Pressable key={key} onPress={() => setFreq(key)} style={[styles.freq, { borderColor: frequency === key ? colors.primary : colors.border, backgroundColor: frequency === key ? colors.primary + "18" : colors.surface }]}><Text style={{ color: frequency === key ? colors.primary : colors.muted, fontWeight: "700" }}>{label}</Text></Pressable>)}</View></Section>
    <Section title={`سەتڵی زبڵ (${trash.length})`} icon="delete-sweep" colors={colors}>{trash.length ? <>{trash.map((item) => <View key={item.id} style={styles.trash}><View style={{ flex: 1 }}><Text style={{ color: colors.foreground, fontWeight: "700" }}>{item.customerName}</Text><Text style={{ color: colors.muted, fontSize: 11 }}>{item.city} · {item.productPrice.toLocaleString("en-US")} د.ع</Text></View><Pressable onPress={() => restoreOrder(item.id)}><Text style={{ color: colors.success, fontWeight: "700" }}>گەڕاندنەوە</Text></Pressable></View>)}<Pressable onPress={confirmTrash} style={[styles.danger, { borderColor: colors.error }]}><Text style={{ color: colors.error, fontWeight: "700" }}>بەتاڵکردنی سەتڵ</Text></Pressable></> : <Text style={{ color: colors.muted }}>سەتڵ بەتاڵە.</Text>}</Section>
    <Text style={[styles.footer, { color: colors.muted }]}>ئۆردەرەکان · وەشانی 1.0.0 · سوپاس</Text>
  </ScrollView></ScreenContainer>;
}
function Section({ title, icon, children, colors }: any) { return <View style={[styles.section, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.sectionHead}><MaterialIcons name={icon} size={20} color={colors.primary} /><Text style={[styles.sectionTitle, { color: colors.foreground }]}>{title}</Text></View>{children}</View>; }
function Row({ label, children, colors }: any) { return <View style={styles.row}><Text style={{ color: colors.foreground, fontWeight: "700" }}>{label}</Text>{children}</View>; }
function Action({ label, icon, color, onPress }: any) { return <Pressable onPress={onPress} style={[styles.action, { backgroundColor: color + "18", borderColor: color + "66" }]}><MaterialIcons name={icon} size={23} color={color} /><Text style={{ color, fontWeight: "800", fontSize: 12 }}>{label}</Text></Pressable>; }
function SmallButton({ label, color, onPress }: any) { return <Pressable onPress={onPress} style={[styles.small, { backgroundColor: color + "18", borderColor: color + "55" }]}><Text style={{ color, fontSize: 11, fontWeight: "800", textAlign: "center" }}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ content: { padding: 16, paddingBottom: 35 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 17 }, title: { fontSize: 25, fontWeight: "800", textAlign: "right" }, sub: { fontSize: 12, marginTop: 4, textAlign: "right" }, section: { borderRadius: 19, borderWidth: 1, padding: 14, marginBottom: 13 }, sectionHead: { flexDirection: "row", gap: 8, alignItems: "center", marginBottom: 13 }, sectionTitle: { fontSize: 16, fontWeight: "800", flex: 1, textAlign: "right" }, row: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, help: { fontSize: 12, lineHeight: 20, textAlign: "right", marginBottom: 10 }, auth: { gap: 8 }, input: { borderWidth: 1, borderRadius: 11, paddingHorizontal: 12, height: 45, textAlign: "right" }, authRow: { flexDirection: "row", gap: 8 }, small: { flex: 1, borderWidth: 1, borderRadius: 10, paddingVertical: 10 }, logged: { flexDirection: "row", padding: 10, borderRadius: 10, marginTop: 10, alignItems: "center" }, actions: { flexDirection: "row", gap: 7, marginTop: 13 }, action: { flex: 1, height: 72, borderRadius: 13, borderWidth: 1, alignItems: "center", justifyContent: "center", gap: 5 }, freqTitle: { fontSize: 13, fontWeight: "700", marginTop: 15, marginBottom: 8, textAlign: "right" }, freqs: { flexDirection: "row", gap: 7 }, freq: { flex: 1, alignItems: "center", borderWidth: 1, borderRadius: 10, paddingVertical: 10 }, trash: { flexDirection: "row", alignItems: "center", paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: "#ffffff18" }, danger: { alignItems: "center", borderWidth: 1, borderRadius: 10, paddingVertical: 10, marginTop: 12 }, footer: { textAlign: "center", fontSize: 11, marginTop: 8 } });
