import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import * as DocumentPicker from "expo-document-picker";
import * as FileSystem from "expo-file-system/legacy";
import * as MailComposer from "expo-mail-composer";
import * as Notifications from "expo-notifications";
import { useEffect, useState } from "react";
import { Alert, Pressable, ScrollView, Share, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { useThemeContext } from "@/lib/theme-provider";
import { BackupPayload, useOrderStore } from "@/lib/order-store";

const SETTINGS_KEY = "orderakan.settings.v3";
type Frequency = "daily" | "monthly" | "never";

export default function SettingsScreen() {
  const colors = useColors(); const { colorScheme, setColorScheme } = useThemeContext();
  const { exportBackup, importBackup, trash, restoreOrder, emptyTrash } = useOrderStore();
  const [frequency, setFrequency] = useState<Frequency>("never"); const [email, setEmail] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { AsyncStorage.getItem(SETTINGS_KEY).then((raw) => { try { const v = raw ? JSON.parse(raw) : {}; if (v.frequency) setFrequency(v.frequency); if (v.theme) setColorScheme(v.theme); if (v.email) setEmail(v.email); } catch {} }); }, [setColorScheme]);
  const savePrefs = async (next: Frequency) => { setFrequency(next); await AsyncStorage.setItem(SETTINGS_KEY, JSON.stringify({ frequency: next, theme: colorScheme, email })); await Notifications.cancelAllScheduledNotificationsAsync(); if (next !== "never") { const permission = await Notifications.requestPermissionsAsync(); if (permission.granted) await Notifications.scheduleNotificationAsync({ content: { title: "💾 باکئەپەکەت بکە!", body: "تکایە بۆ پاراستنی زانیاریەکانت backup بکە" }, trigger: next === "daily" ? { type: Notifications.SchedulableTriggerInputTypes.DAILY, hour: 20, minute: 0 } : { type: Notifications.SchedulableTriggerInputTypes.MONTHLY, day: 1, hour: 20, minute: 0 } }); } };
  const makeFile = async () => { const uri = `${FileSystem.cacheDirectory}orderakan-backup-${new Date().toISOString().slice(0, 10)}.json`; await FileSystem.writeAsStringAsync(uri, JSON.stringify(exportBackup(), null, 2)); return uri; };
  const sendEmailBackup = async () => { if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim())) { Alert.alert("Email هەڵەیە", "تکایە email ـێکی دروست بنووسە."); return; } setBusy(true); try { const uri = await makeFile(); const available = await MailComposer.isAvailableAsync(); if (!available) { await Share.share({ title: "Backup ـی ئۆردەرەکان", message: JSON.stringify(exportBackup(), null, 2) }); return; } const result = await MailComposer.composeAsync({ recipients: [email.trim()], subject: `Backup ـی ئۆردەرەکان ${new Date().toLocaleDateString("en-GB")}`, body: "Backup ـی داتاکانت بە attachment ـەوە لەم email ـەدایە. تکایە فایلەکە هەڵبگرە.", attachments: [uri] }); if (result.status === "sent" || result.status === "saved") { Alert.alert("سەرکەوتوو بوو", "Backup ـەکە بە attachment ـەوە نێردرا یان پاشەکەوت کرا."); await AsyncStorage.setItem(SETTINGS_KEY, JSON.stringify({ frequency, theme: colorScheme, email: email.trim(), lastBackupAt: new Date().toISOString() })); } } catch { Alert.alert("هەڵە", "ناردنی email سەرکەوتوو نەبوو؛ تکایە email app ـێک لە مۆبایلەکەت دابەزێنە."); } finally { setBusy(false); } };
  const restoreFromFile = async () => { const result = await DocumentPicker.getDocumentAsync({ type: "application/json", copyToCacheDirectory: true }); if (result.canceled) return; Alert.alert("گەڕاندنەوەی backup", "دڵنیایت داتای ئێستا بە داتای فایلەکە بگۆڕدرێت؟", [{ text: "نەخێر", style: "cancel" }, { text: "بەڵێ", onPress: async () => { setBusy(true); try { const raw = await FileSystem.readAsStringAsync(result.assets[0].uri); const payload = JSON.parse(raw) as BackupPayload; if (!payload.months || !payload.orders) throw new Error("invalid"); importBackup(payload); Alert.alert("سەرکەوتوو بوو", "هەموو مانگ و ئۆردەرەکانت بە هەمان بەروار و نرخ گەڕێندرایەوە."); } catch { Alert.alert("هەڵە", "فایلەکە backup ـێکی دروست نییە."); } finally { setBusy(false); } } }]); };
  const chooseFrequency = () => Alert.alert("Backup ـی خۆکار", "هەڵبژاردەی backup ـت دیاری بکە", [{ text: "رۆژانە", onPress: () => savePrefs("daily") }, { text: "مانگانە", onPress: () => savePrefs("monthly") }, { text: "هەرگیز", onPress: () => savePrefs("never") }, { text: "پاشگەزبوونەوە", style: "cancel" }]);
  const confirmTrash = () => Alert.alert("سڕینەوەی هەمیشەیی", "دڵنیایت لە بەتاڵکردنی Trash؟", [{ text: "نەخێر", style: "cancel" }, { text: "بەڵێ", style: "destructive", onPress: emptyTrash }]);
  return <ScreenContainer edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.content}>
    <View style={styles.header}><View><Text style={[styles.title, { color: colors.foreground }]}>ڕێکخستن</Text><Text style={[styles.sub, { color: colors.muted }]}>پاراستنی داتا و ڕێکخستنی ئەپ</Text></View><MaterialIcons name="settings" size={28} color={colors.primary} /></View>
    <Section title="ڕووکار" icon="palette" colors={colors}><View style={styles.row}><Text style={{ color: colors.foreground, fontWeight: "700" }}>Dark mode</Text><Switch value={colorScheme === "dark"} onValueChange={async (v) => { const theme = v ? "dark" : "light"; setColorScheme(theme); await AsyncStorage.setItem(SETTINGS_KEY, JSON.stringify({ frequency, theme, email })); }} /></View></Section>
    <Section title="باکئەپی داتاکان لە ڕێگای ئیمەیڵ" icon="backup" colors={colors}><Text style={[styles.help, { color: colors.muted }]}>بۆ ئەوەی داتاکانت بە پارێزراوی بهێڵیتەوە باکئەپ بکە</Text><TextInput value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" placeholder="ئیمەیڵەکەت بنووسە" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.background }]} /><View style={styles.actions}><Action label="Backup بۆ Email" icon="email" color={colors.primary} onPress={sendEmailBackup} /><Action label="Restore لە فایل" icon="restore" color={colors.success} onPress={restoreFromFile} /></View><Pressable disabled={busy} onPress={chooseFrequency} style={[styles.mainButton, { backgroundColor: colors.primary }]}><MaterialIcons name="schedule" size={20} color="#fff" /><Text style={styles.mainButtonText}>Backup ـی خۆکار: {frequency === "daily" ? "رۆژانە" : frequency === "monthly" ? "مانگانە" : "هەرگیز"}</Text></Pressable></Section>
    <Section title={`Trash (${trash.length})`} icon="delete-sweep" colors={colors}><Text style={[styles.help, { color: colors.muted }]}>گەڕاندنەوەی ئاسانی ئەو زانیاریانەی بە هەڵە سڕیوتونەتەوە!</Text>{trash.length ? <>{trash.map((item) => <View key={item.id} style={styles.trash}><View style={{ flex: 1 }}><Text style={{ color: colors.foreground, fontWeight: "700" }}>{item.customerName}</Text><Text style={{ color: colors.muted, fontSize: 11 }}>{item.city} · {item.productPrice.toLocaleString("en-US")} د.ع</Text></View><Pressable onPress={() => restoreOrder(item.id)}><Text style={{ color: colors.success, fontWeight: "700" }}>گەڕاندنەوە</Text></Pressable></View>)}<Pressable onPress={confirmTrash} style={[styles.danger, { borderColor: colors.error }]}><Text style={{ color: colors.error, fontWeight: "700" }}>بەتاڵکردنی Trash</Text></Pressable></> : <Text style={{ color: colors.muted }}>Trash بەتاڵە.</Text>}</Section>
    <Text style={[styles.footer, { color: colors.muted }]}>ئۆردەرەکان · وەشانی 1.0.2</Text>
  </ScrollView></ScreenContainer>;
}
function Section({ title, icon, children, colors }: any) { return <View style={[styles.section, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.sectionHead}><MaterialIcons name={icon} size={20} color={colors.primary} /><Text style={[styles.sectionTitle, { color: colors.foreground }]}>{title}</Text></View>{children}</View>; }
function Action({ label, icon, color, onPress }: any) { return <Pressable onPress={onPress} style={[styles.action, { backgroundColor: color + "18", borderColor: color + "66" }]}><MaterialIcons name={icon} size={23} color={color} /><Text style={{ color, fontWeight: "800", fontSize: 11, textAlign: "center" }}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ content: { padding: 16, paddingBottom: 35 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 17 }, title: { fontSize: 25, fontWeight: "800", textAlign: "right" }, sub: { fontSize: 12, marginTop: 4, textAlign: "right" }, section: { borderRadius: 19, borderWidth: 1, padding: 14, marginBottom: 13 }, sectionHead: { flexDirection: "row", gap: 8, alignItems: "center", marginBottom: 13 }, sectionTitle: { fontSize: 16, fontWeight: "800", flex: 1, textAlign: "right" }, row: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, help: { fontSize: 12, lineHeight: 20, textAlign: "right", marginBottom: 11 }, input: { borderWidth: 1, borderRadius: 11, height: 46, paddingHorizontal: 12, textAlign: "right", marginBottom: 10 }, actions: { flexDirection: "row", gap: 8 }, action: { flex: 1, height: 72, borderRadius: 13, borderWidth: 1, alignItems: "center", justifyContent: "center", gap: 5 }, mainButton: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, borderRadius: 12, paddingVertical: 13, marginTop: 10 }, mainButtonText: { color: "#fff", fontWeight: "800", fontSize: 13 }, trash: { flexDirection: "row", alignItems: "center", paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: "#ffffff18" }, danger: { alignItems: "center", borderWidth: 1, borderRadius: 10, paddingVertical: 10, marginTop: 12 }, footer: { textAlign: "center", fontSize: 11, marginTop: 8 } });
